"""Typed attribute/method surface shared by the Casper mixins.

Runtime-empty: the ``TYPE_CHECKING`` block only exists so each mixin's
``self.<attr>`` / ``self.<method>`` references resolve for readers and type
checkers. The real implementations live on the composed ``Casper`` class.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import asyncio

    from langchain_anthropic import ChatAnthropic
    from langchain_core.messages import SystemMessage, ToolMessage
    from langgraph.graph import MessagesState

    from app.adapters.grep_agent_2 import PdfSession
    from app.research.agent._state import CasperState, UpdatedProposedReportLayout


class CasperBase:
    """Shared attribute + cross-mixin method declarations (typing only)."""

    if TYPE_CHECKING:
        # --- instance attributes (set in Casper.__init__ / _initialize_components) ---
        user_name: str
        chat_id: str
        forced_report_type: Any
        report_in_progress: bool
        in_progress_report_id: str | None
        in_progress_report_title: str | None
        openai_upload_file_config: dict | None
        file_search_mode: str
        upload_file_config: dict | None
        grep_session: PdfSession | None
        web_search: bool
        domain_name: str
        domain_id: str
        mcp_server_url: str
        retrieve_config: dict
        user_id: str | None
        _current_turn_messages: list
        _background_tasks: set
        updated_proposed_report_layout: UpdatedProposedReportLayout | None
        _layout_refresh_task: asyncio.Task | None
        turn_thread_id: str
        report_layout_pair: dict
        report_config_submission: dict
        card_style: str
        _resuming_report_config: bool
        prioritize_arxiv: Any
        user_previous_messages: list
        s3_instance: Any
        anthropic_llm: ChatAnthropic
        system_message: SystemMessage
        graph: Any
        _pr_subgraph: Any
        _dd_subgraph: Any
        _latest_info_context: list

        # --- cross-mixin methods (implemented on other mixins) ---
        def _has_uploaded_documents(self) -> bool: ...
        def _uses_grep_file_search(self) -> bool: ...
        def _fallback_to_openai_file_search(self) -> bool: ...
        async def _await_layout_refresh(self, timeout: float = ...) -> None: ...
        def _patched_layout_tool_message(self, messages: list) -> ToolMessage | None: ...
        def _spawn_background_task(self, coro: Any) -> asyncio.Task: ...
        def _layout_ever_proposed(self, messages: list) -> bool: ...
        def _pending_retrieve_call(self, messages: list) -> dict[str, Any] | None: ...
        def _count_turn_tool_calls(self, messages: list) -> tuple[int, int]: ...
        def _get_recent_tool_messages(self, messages: list) -> list: ...
        def graph_config(self) -> dict[str, Any]: ...
        async def retrieve(self, *args: Any, **kwargs: Any) -> Any: ...
        async def query_document(self, *args: Any, **kwargs: Any) -> Any: ...
        async def retrieve_latest_info(self, *args: Any, **kwargs: Any) -> Any: ...
        async def ask_user(self, questions: list[str]) -> str: ...
        async def propose_report_layout(self, *args: Any, **kwargs: Any) -> Any: ...
        async def update_proposed_report_layout(self, *args: Any, **kwargs: Any) -> Any: ...
        async def report_or_respond(self, state: MessagesState) -> dict[str, list]: ...
        async def respond_during_report(self, state: MessagesState) -> dict[str, list]: ...
        async def generate_report(self, state: MessagesState) -> dict[str, list]: ...
        async def _dispatch_read_tool(self, name: str, args: dict[str, Any]) -> str: ...
        async def _web_refreshed_layout(self, *args: Any, **kwargs: Any) -> Any: ...
        async def _mint_sibling_layout(self, *args: Any, **kwargs: Any) -> Any: ...
        async def _parsed_layout_cards(self, layout_markdown: str) -> list[dict]: ...
        def _extract_in_progress_layout(self, messages: list) -> str: ...
        def _route_entry(self, state: MessagesState) -> str: ...
        def _route_after_report_or_respond(self, state: MessagesState) -> str: ...
        def _route_after_gate(self, state: MessagesState) -> str: ...
        def _route_after_tools(self, state: MessagesState) -> str: ...
        def _route_by_domain(self, state: MessagesState) -> str: ...
        async def domain_router(self, state: MessagesState) -> MessagesState: ...
        async def run_primary_research(self, state: MessagesState) -> dict[str, list]: ...
        async def run_due_diligence(self, state: MessagesState) -> dict[str, list]: ...
        async def _sequential_tools_node(self, state: MessagesState) -> dict[str, list]: ...
        def _gate_node(self, state: MessagesState) -> dict[str, list]: ...
        async def layout_pair(self, state: CasperState) -> dict[str, Any]: ...
        async def report_config(self, state: CasperState) -> dict[str, Any]: ...
        async def _build_graph(self) -> Any: ...
        async def paused_report_or_respond_update(self) -> dict[str, Any] | None: ...
        async def _upload_report_layout_to_s3_background(self, *a: Any, **k: Any) -> None: ...
        async def _upload_descriptive_layout_to_s3_background(self, *a: Any, **k: Any) -> None: ...
        async def _upload_card_to_s3_background(self, card: dict, card_name: str) -> None: ...
        async def _upload_fixed_card_to_s3_background(self, card: dict, card_name: str) -> None: ...
        async def _upload_cards_for_db_to_s3_background(self, *a: Any, **k: Any) -> None: ...
        def _grep_result_failed(self, result: dict, answer: str) -> bool: ...
        async def _query_document_openai(self, user_query: str) -> str: ...
        async def _query_document_grep(self, user_query: str) -> str: ...
        def _emit_card_step(self, event_writer: Any, section_name: str, step: str) -> None: ...
        async def _prepare_card_through_pipeline(self, *a: Any, **k: Any) -> Any: ...
        async def _process_card_through_pipeline(self, *a: Any, **k: Any) -> Any: ...
        async def _process_brief_card_task(self, *a: Any, **k: Any) -> Any: ...
