"""Added 2 new tables: subscribers and requests

Revision ID: 1585890b7b93
Revises: 9a386e0edf08
Create Date: 2025-09-20 22:52:25.181750

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1585890b7b93"
down_revision: str | None = "9a386e0edf08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Name of the person making the request",
        ),
        sa.Column(
            "email", sa.String(length=255), nullable=False, comment="Email address of the requester"
        ),
        sa.Column(
            "website", sa.String(length=500), nullable=True, comment="Website URL of the requester"
        ),
        sa.Column("description", sa.Text(), nullable=False, comment="Description of the request"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when request was created",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_requests_email", "requests", ["email"], unique=False)

    op.create_table(
        "subscribers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="Email address of the subscriber",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when subscriber was created in UTC",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_subscribers_email", "subscribers", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_subscribers_email", table_name="subscribers")
    op.drop_table("subscribers")
    op.drop_index("idx_requests_email", table_name="requests")
    op.drop_table("requests")
    # ### end Alembic commands ###
