"""wallet migration

Revision ID: 567be0211968
Revises: 91e7c49150db
Create Date: 2026-01-24 19:43:51.141564

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "567be0211968"
down_revision: str | None = "91e7c49150db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column(
            "user_id",
            sa.CHAR(length=36),
            nullable=False,
            comment="Reference to user (one subscription per user)",
        ),
        sa.Column(
            "razorpay_subscription_id",
            sa.CHAR(length=100),
            nullable=True,
            comment="Reference to razorpay subscription id",
        ),
        sa.Column(
            "current_tier",
            sa.Enum("FREE", "PLUS", "PRO", name="subscription_tier_enum"),
            nullable=False,
            comment="Current tier: free, plus, pro",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "EXPIRED",
                "CANCELLED",
                "REFUNDED",
                "PAUSED",
                "PENDING",
                name="subscription_status_enum",
            ),
            nullable=False,
            comment="Status: active, expired, cancelled, refunded, paused",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "idx_subscriptions_current_tier", "subscriptions", ["current_tier"], unique=False
    )
    op.create_index(
        "idx_subscriptions_razorpay_id", "subscriptions", ["razorpay_subscription_id"], unique=False
    )
    op.create_index("idx_subscriptions_status", "subscriptions", ["status"], unique=False)
    op.create_index("idx_subscriptions_user_id", "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "wallets",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column(
            "user_id",
            sa.CHAR(length=36),
            nullable=False,
            comment="Reference to user (one wallet per user)",
        ),
        sa.Column(
            "available_balance", sa.Integer(), nullable=False, comment="Tokens available for use"
        ),
        sa.Column(
            "reserved_balance",
            sa.Integer(),
            nullable=False,
            comment="Tokens locked for pending operations",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("idx_wallets_user_id", "wallets", ["user_id"], unique=False)
    op.create_table(
        "token_batches",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("wallet_id", sa.CHAR(length=36), nullable=False, comment="Reference to wallet"),
        sa.Column(
            "idempotency_key",
            sa.String(length=100),
            nullable=True,
            comment="Idempotency key for payment",
        ),
        sa.Column(
            "initial_tokens", sa.Integer(), nullable=False, comment="Original tokens in batch"
        ),
        sa.Column(
            "remaining_tokens",
            sa.Integer(),
            nullable=False,
            comment="Available tokens (source of truth for balance)",
        ),
        sa.Column(
            "reserved_tokens",
            sa.Integer(),
            nullable=False,
            comment="Tokens locked for pending operations",
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Amount paid for this batch",
        ),
        sa.Column(
            "currency",
            sa.String(length=10),
            nullable=False,
            comment="Currency: USD, INR, EUR, etc.",
        ),
        sa.Column(
            "source_type",
            sa.Enum(
                "SIGNUP_BONUS",
                "SUBSCRIPTION",
                "TOPUP",
                "REPORT_GENERATION",
                "REFUND",
                "EXPIRY",
                name="transaction_source_enum",
            ),
            nullable=False,
            comment="Source: signup_bonus, subscription, topup, report_generation, refund, expiry",
        ),
        sa.Column(
            "payment_id",
            sa.String(length=50),
            nullable=True,
            comment="Reference to payment_id in payment service",
        ),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "PENDING", "FAILED", "REVERSED", name="transaction_status_enum"),
            nullable=False,
            comment="Status: completed, pending, failed",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this batch expires",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        "idx_token_batches_balance_calc", "token_batches", ["wallet_id", "expires_at"], unique=False
    )
    op.create_index("idx_token_batches_expires_at", "token_batches", ["expires_at"], unique=False)
    op.create_index("idx_token_batches_payment_id", "token_batches", ["payment_id"], unique=False)
    op.create_index("idx_token_batches_source_type", "token_batches", ["source_type"], unique=False)
    op.create_index("idx_token_batches_wallet_id", "token_batches", ["wallet_id"], unique=False)
    op.create_index(
        op.f("ix_token_batches_payment_id"), "token_batches", ["payment_id"], unique=False
    )
    op.create_table(
        "subscription_intervals",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column(
            "subscription_id",
            sa.CHAR(length=36),
            nullable=False,
            comment="Reference to parent subscription",
        ),
        sa.Column(
            "tier",
            sa.Enum("FREE", "PLUS", "PRO", name="subscription_tier_enum"),
            nullable=False,
            comment="Subscription tier for this interval: plus, pro",
        ),
        sa.Column(
            "start_date",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Start of billing interval",
        ),
        sa.Column(
            "end_date",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="End of billing interval",
        ),
        sa.Column(
            "payment_id",
            sa.String(length=50),
            nullable=False,
            comment="Reference to payment_id in payment service",
        ),
        sa.Column(
            "amount", sa.Numeric(precision=10, scale=2), nullable=True, comment="Amount charged"
        ),
        sa.Column("currency", sa.String(length=10), nullable=True, comment="Currency of payment"),
        sa.Column(
            "tokens_credited",
            sa.Integer(),
            nullable=False,
            comment="Tokens credited for this interval",
        ),
        sa.Column(
            "token_batch_id",
            sa.CHAR(length=36),
            nullable=True,
            comment="Reference to token batch created",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "EXPIRED",
                "CANCELLED",
                "REFUNDED",
                "PAUSED",
                "PENDING",
                name="subscription_status_enum",
            ),
            nullable=False,
            comment="Status: active, expired, cancelled, refunded",
        ),
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional details like next autopay schedule date, payment method and other payment related data",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["token_batch_id"], ["token_batches.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        "idx_subscription_intervals_active_lookup",
        "subscription_intervals",
        ["subscription_id", "status", "end_date"],
        unique=False,
    )
    op.create_index(
        "idx_subscription_intervals_end_date", "subscription_intervals", ["end_date"], unique=False
    )
    op.create_index(
        "idx_subscription_intervals_payment_id",
        "subscription_intervals",
        ["payment_id"],
        unique=False,
    )
    op.create_index(
        "idx_subscription_intervals_start_date",
        "subscription_intervals",
        ["start_date"],
        unique=False,
    )
    op.create_index(
        "idx_subscription_intervals_status", "subscription_intervals", ["status"], unique=False
    )
    op.create_index(
        "idx_subscription_intervals_subscription_id",
        "subscription_intervals",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "idx_subscription_intervals_tier", "subscription_intervals", ["tier"], unique=False
    )
    op.create_index(
        op.f("ix_subscription_intervals_payment_id"),
        "subscription_intervals",
        ["payment_id"],
        unique=False,
    )
    op.create_table(
        "token_transactions",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("wallet_id", sa.CHAR(length=36), nullable=False, comment="Reference to wallet"),
        sa.Column(
            "transaction_type",
            sa.Enum("CREDIT", "DEBIT", "RESERVE", "RELEASE", name="transaction_type_enum"),
            nullable=False,
            comment="Type: credit, debit, reserve, release",
        ),
        sa.Column(
            "source_type",
            sa.Enum(
                "SIGNUP_BONUS",
                "SUBSCRIPTION",
                "TOPUP",
                "REPORT_GENERATION",
                "REFUND",
                "EXPIRY",
                name="transaction_source_enum",
            ),
            nullable=False,
            comment="Source: signup_bonus, subscription, topup, report_generation, refund, expiry",
        ),
        sa.Column(
            "tokens",
            sa.Integer(),
            nullable=False,
            comment="Token amount (+ve for credit, -ve for debit)",
        ),
        sa.Column(
            "balance_after",
            sa.Integer(),
            nullable=False,
            comment="Available balance snapshot after transaction",
        ),
        sa.Column(
            "reserved_after",
            sa.Integer(),
            nullable=False,
            comment="Reserved balance snapshot after transaction",
        ),
        sa.Column(
            "report_id",
            sa.CHAR(length=36),
            nullable=True,
            comment="Reference to report (if applicable)",
        ),
        sa.Column(
            "token_batch_id",
            sa.CHAR(length=36),
            nullable=True,
            comment="Reference to primary affected token batch",
        ),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "PENDING", "FAILED", "REVERSED", name="transaction_status_enum"),
            nullable=False,
            comment="Status: completed, pending, failed, reversed",
        ),
        sa.Column(
            "description",
            sa.String(length=255),
            nullable=True,
            comment="Human-readable description",
        ),
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional data (error messages, token_batch_ids for multi-batch operations, etc.)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["token_batch_id"], ["token_batches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        "idx_token_transactions_created_at", "token_transactions", ["created_at"], unique=False
    )
    op.create_index(
        "idx_token_transactions_report_id", "token_transactions", ["report_id"], unique=False
    )
    op.create_index(
        "idx_token_transactions_source_type", "token_transactions", ["source_type"], unique=False
    )
    op.create_index("idx_token_transactions_status", "token_transactions", ["status"], unique=False)
    op.create_index(
        "idx_token_transactions_token_batch_id",
        "token_transactions",
        ["token_batch_id"],
        unique=False,
    )
    op.create_index(
        "idx_token_transactions_transaction_type",
        "token_transactions",
        ["transaction_type"],
        unique=False,
    )
    op.create_index(
        "idx_token_transactions_wallet_id", "token_transactions", ["wallet_id"], unique=False
    )
    op.create_index(
        op.f("ix_token_transactions_report_id"), "token_transactions", ["report_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_transactions_report_id"), table_name="token_transactions")
    op.drop_index("idx_token_transactions_wallet_id", table_name="token_transactions")
    op.drop_index("idx_token_transactions_transaction_type", table_name="token_transactions")
    op.drop_index("idx_token_transactions_token_batch_id", table_name="token_transactions")
    op.drop_index("idx_token_transactions_status", table_name="token_transactions")
    op.drop_index("idx_token_transactions_source_type", table_name="token_transactions")
    op.drop_index("idx_token_transactions_report_id", table_name="token_transactions")
    op.drop_index("idx_token_transactions_created_at", table_name="token_transactions")
    op.drop_table("token_transactions")
    op.drop_index(op.f("ix_subscription_intervals_payment_id"), table_name="subscription_intervals")
    op.drop_index("idx_subscription_intervals_tier", table_name="subscription_intervals")
    op.drop_index("idx_subscription_intervals_subscription_id", table_name="subscription_intervals")
    op.drop_index("idx_subscription_intervals_status", table_name="subscription_intervals")
    op.drop_index("idx_subscription_intervals_start_date", table_name="subscription_intervals")
    op.drop_index("idx_subscription_intervals_payment_id", table_name="subscription_intervals")
    op.drop_index("idx_subscription_intervals_end_date", table_name="subscription_intervals")
    op.drop_index("idx_subscription_intervals_active_lookup", table_name="subscription_intervals")
    op.drop_table("subscription_intervals")
    op.drop_index(op.f("ix_token_batches_payment_id"), table_name="token_batches")
    op.drop_index("idx_token_batches_wallet_id", table_name="token_batches")
    op.drop_index("idx_token_batches_source_type", table_name="token_batches")
    op.drop_index("idx_token_batches_payment_id", table_name="token_batches")
    op.drop_index("idx_token_batches_expires_at", table_name="token_batches")
    op.drop_index("idx_token_batches_balance_calc", table_name="token_batches")
    op.drop_table("token_batches")
    op.drop_index("idx_wallets_user_id", table_name="wallets")
    op.drop_table("wallets")
    op.drop_index("idx_subscriptions_user_id", table_name="subscriptions")
    op.drop_index("idx_subscriptions_status", table_name="subscriptions")
    op.drop_index("idx_subscriptions_razorpay_id", table_name="subscriptions")
    op.drop_index("idx_subscriptions_current_tier", table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
