"""subscription table migration

Revision ID: 8f81976940e6
Revises: 04e46567fad2
Create Date: 2026-01-26 16:02:30.989330

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8f81976940e6"
down_revision: str | None = "04e46567fad2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Subscription table changes - main focus of this migration
    op.add_column(
        "subscriptions",
        sa.Column(
            "subscription_id",
            sa.CHAR(length=100),
            nullable=True,
            comment="Reference to external subscription id",
        ),
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional metadata",
        ),
    )
    op.drop_index(op.f("idx_subscriptions_razorpay_id"), table_name="subscriptions")
    op.create_index(
        "idx_subscriptions_external_id", "subscriptions", ["subscription_id"], unique=False
    )
    op.drop_column("subscriptions", "razorpay_subscription_id")

    # Token batches - make currency nullable
    op.alter_column(
        "token_batches",
        "currency",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
        existing_comment="Currency: USD, INR, EUR, etc.",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Token batches - revert currency to not nullable
    op.alter_column(
        "token_batches",
        "currency",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
        existing_comment="Currency: USD, INR, EUR, etc.",
    )

    # Subscription table changes - revert to razorpay_subscription_id
    op.add_column(
        "subscriptions",
        sa.Column(
            "razorpay_subscription_id",
            sa.CHAR(length=100),
            autoincrement=False,
            nullable=True,
            comment="Reference to razorpay subscription id",
        ),
    )
    op.drop_index("idx_subscriptions_external_id", table_name="subscriptions")
    op.create_index(
        op.f("idx_subscriptions_razorpay_id"),
        "subscriptions",
        ["razorpay_subscription_id"],
        unique=False,
    )
    op.drop_column("subscriptions", "meta_data")
    op.drop_column("subscriptions", "subscription_id")

    # ### end Alembic commands ###
