"""add initial schema

Revision ID: 9a386e0edf08
Revises:
Create Date: 2025-09-18 11:12:17.329919

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a386e0edf08"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create users table
    op.create_table(
        "users",
        sa.Column("id", sa.CHAR(36), primary_key=True, nullable=False),
        sa.Column("email", sa.String(255), unique=True, nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("phone", sa.String(20), unique=True, nullable=False),
        sa.Column("phone_country_code", sa.String(8), nullable=True),
        sa.Column("user_name", sa.String(255), nullable=True),
        sa.Column("is_google_verified", sa.Boolean(), default=False, nullable=False),
        sa.Column("is_verified", sa.Boolean(), default=False, nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index("idx_users_email", "users", ["email"])
    op.create_index("idx_users_phone", "users", ["phone"])

    # Create messages table
    op.create_table(
        "messages",
        sa.Column("id", sa.CHAR(36), primary_key=True, nullable=False, comment="Chat identifier"),
        sa.Column(
            "user_id",
            sa.CHAR(36),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            comment="Reference to the user",
        ),
        sa.Column("chat_title", sa.String(255), nullable=True, comment="Title of the chat"),
        sa.Column(
            "chat_messages",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Complete message data stored as JSONB",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when message was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when message was last updated",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether the chat has been deleted by the user",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the chat was deleted",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index("idx_messages_user_id", "messages", ["user_id"])
    op.create_index("idx_messages_is_deleted", "messages", ["is_deleted"])

    # Create reports table
    op.create_table(
        "reports",
        sa.Column("id", sa.CHAR(36), primary_key=True, nullable=False),
        sa.Column(
            "chat_id",
            sa.CHAR(36),
            sa.ForeignKey("messages.id", ondelete="CASCADE"),
            nullable=False,
            comment="Reference to the chat/message",
        ),
        sa.Column(
            "s3_uri",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="S3 URIs to the report files in JSON format {file_type: s3_path}",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when report markdown was generated",
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp final when report was generated in UTC",
        ),
        sa.Column("title", sa.String(255), nullable=True, comment="Title of the report"),
        sa.Column(
            "layout",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Layout configuration for the report",
        ),
        sa.Column(
            "length",
            sa.String(50),
            nullable=True,
            comment="Length description of the report (comprehensive/overview)",
        ),
        sa.Column("summary", sa.Text(), nullable=True, comment="Summary of the report"),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Citations or references used in the report",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index("idx_reports_chat_id", "reports", ["chat_id"])

    # Create cards table
    op.create_table(
        "cards",
        sa.Column(
            "id",
            sa.CHAR(36),
            primary_key=True,
            nullable=False,
            comment="parent card id since we have to store version of the card",
        ),
        sa.Column("card_id", sa.CHAR(36), nullable=False, comment="Card identifier"),
        sa.Column(
            "report_id",
            sa.CHAR(36),
            sa.ForeignKey("reports.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=True, comment="Title of the card"),
        sa.Column(
            "sequence",
            sa.Integer(),
            nullable=False,
            comment="Sequence to preserve order in the report",
        ),
        sa.Column(
            "sub_sections",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Sub section of the card",
        ),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Content of the card",
        ),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Citations or references specific to this card",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True, comment="Summary of the card content"),
        sa.Column(
            "type",
            sa.String(50),
            nullable=True,
            comment="Type of the card (title/subtitle/toc/section/viz)",
        ),
        sa.Column("version", sa.Integer(), nullable=True, comment="Version of the card"),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
            comment="Whether the card is active",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
            comment="Whether the card is deleted",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index("idx_cards_id", "cards", ["id"])
    op.create_index("idx_cards_card_id", "cards", ["card_id"])
    op.create_index("idx_cards_report_id", "cards", ["report_id"])
    op.create_index("idx_cards_sequence", "cards", ["sequence"])

    # Create card_versions table
    op.create_table(
        "card_versions",
        sa.Column("id", sa.CHAR(36), primary_key=True, nullable=False),
        sa.Column(
            "parent_card_id",
            sa.CHAR(36),
            sa.ForeignKey("cards.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_instruction", sa.Text(), nullable=True, comment="User instruction for the card"
        ),
        sa.Column(
            "refinement_type",
            sa.String(50),
            nullable=True,
            comment="Refinement type section,subsection or visualization",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index("idx_card_versions_parent_card_id", "card_versions", ["parent_card_id"])
    op.create_index("idx_card_versions_refinement_type", "card_versions", ["refinement_type"])

    # Create publish table
    op.create_table(
        "publish",
        sa.Column("id", sa.CHAR(36), primary_key=True, nullable=False),
        sa.Column(
            "report_id",
            sa.CHAR(36),
            sa.ForeignKey("reports.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "faq",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Frequently asked questions related to the report",
        ),
        sa.Column(
            "insights",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Key insights from the report",
        ),
        sa.Column(
            "industries_jobs",
            sa.Text(),
            nullable=True,
            comment="Industries or job sectors the report is relevant to",
        ),
        sa.Column(
            "geographic_areas",
            sa.Text(),
            nullable=True,
            comment="Geographic areas covered in the report",
        ),
        sa.Column(
            "special_emphasis",
            sa.Text(),
            nullable=True,
            comment="Special areas of emphasis in the report",
        ),
        sa.Column("audience", sa.Text(), nullable=True, comment="Target audience for the report"),
        sa.Column("purpose", sa.Text(), nullable=True, comment="Purpose of the report"),
        sa.Column(
            "overview", sa.Text(), nullable=True, comment="Overview or summary of the report"
        ),
        sa.Column(
            "media_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Details about media elements in the report (poster_id, heygen_video_id, heygen_folder_id)",
        ),
        sa.Column(
            "page_count", sa.Integer(), nullable=True, comment="Number of pages in the report"
        ),
        sa.Column(
            "source_count",
            sa.Integer(),
            nullable=True,
            comment="Number of sources cited in the report",
        ),
        sa.Column(
            "table_count", sa.Integer(), nullable=True, comment="Number of tables in the report"
        ),
        sa.Column(
            "viz_count",
            sa.Integer(),
            nullable=True,
            comment="Number of visualizations in the report",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index("idx_publish_report_id", "publish", ["report_id"])

    # Create tables table
    op.create_table(
        "tables",
        sa.Column("id", sa.CHAR(36), primary_key=True, nullable=False),
        sa.Column(
            "report_id",
            sa.CHAR(36),
            sa.ForeignKey("reports.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "parent_card_id",
            sa.CHAR(36),
            sa.ForeignKey("cards.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("table_id", sa.String(255), nullable=False),
        sa.Column("table_title", sa.Text(), nullable=True),
        sa.Column("table_markdown", sa.Text(), nullable=True),
        sa.Column(
            "base64_s3_uri",
            sa.Text(),
            nullable=True,
            comment="S3 URI for the visualization image converted from base64",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index("idx_tables_report_id", "tables", ["report_id"])
    op.create_index("idx_tables_table_id", "tables", ["table_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tables")
    op.drop_table("publish")
    op.drop_table("card_versions")
    op.drop_table("cards")
    op.drop_table("reports")
    op.drop_table("messages")
    op.drop_table("users")
    # ### end Alembic commands ###
