"""report versioning added

Revision ID: b9872c6eaf60
Revises: eb19fa22cf92
Create Date: 2025-11-12 15:27:26.743606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9872c6eaf60'
down_revision: Union[str, None] = 'eb19fa22cf92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_versions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('report_id', sa.CHAR(length=36), nullable=False, comment='Reference to the base report'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number'),
    sa.Column('s3_uri', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='S3 URIs for this version {file_type: s3_path}'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True, comment='When this version was generated'),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true', comment='Whether this is the active version'),
    sa.Column('status', sa.String(length=50), nullable=False, server_default='draft', comment='Status of this version'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last activity timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_report_versions_is_active', 'report_versions', ['is_active'], unique=False)
    op.create_index('idx_report_versions_report_id', 'report_versions', ['report_id'], unique=False)
    op.create_index('idx_report_versions_status', 'report_versions', ['status'], unique=False)
    op.create_index('idx_report_versions_version', 'report_versions', ['version'], unique=False)
    op.create_table('report_version_cards',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('report_version_id', sa.CHAR(length=36), nullable=False, comment='Reference to report version'),
    sa.Column('parent_card_id', sa.CHAR(length=36), nullable=False, comment='Reference to card table primary key (cards.id)'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Position in this version'),
    sa.Column('is_modified', sa.Boolean(), nullable=False, server_default='false', comment='Whether card was modified in this version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_report_version_cards_parent_card_id', 'report_version_cards', ['parent_card_id'], unique=False)
    op.create_index('idx_report_version_cards_sequence', 'report_version_cards', ['sequence'], unique=False)
    op.create_index('idx_report_version_cards_version_id', 'report_version_cards', ['report_version_id'], unique=False)
    op.create_unique_constraint(None, 'card_versions', ['id'])
    op.alter_column('cards', 'id',
               existing_type=sa.CHAR(length=36),
               comment='Primary key - unique for each card instance',
               existing_comment='parent card id since we have to store version of the card',
               existing_nullable=False)
    op.alter_column('cards', 'card_id',
               existing_type=sa.CHAR(length=36),
               comment='Business card identifier - links versions of same logical card',
               existing_comment='Card identifier',
               existing_nullable=False)
    op.alter_column('cards', 'report_id',
               existing_type=sa.CHAR(length=36),
               comment='Reference to base report for filtering',
               existing_nullable=False)
    op.alter_column('cards', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Whether the card is active',
               existing_nullable=False)
    op.alter_column('cards', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Whether the card is deleted',
               existing_nullable=False)
    op.create_unique_constraint(None, 'cards', ['id'])
    op.alter_column('messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Whether the chat has been deleted by the user',
               existing_nullable=False)
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'publish', ['id'])
    op.add_column('reports', sa.Column('poster_image_url', sa.String(length=500), nullable=True, comment='CDN URL for the poster/thumbnail image'))
    op.add_column('reports', sa.Column('current_version', sa.Integer(), nullable=False, server_default='1', comment='Current active version number'))
    op.add_column('reports', sa.Column('status', sa.String(length=50), nullable=False, server_default='draft', comment='Overall status of the report'))
    op.add_column('reports', sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last activity timestamp'))
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when report was first created',
               existing_comment='Timestamp when report markdown was generated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 's3_uri',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default='{"md": null, "pdf": null, "html": null, "pptx": null}',
               comment='S3 URIs of current version (denormalized for quick access)',
               existing_comment='S3 URIs to the report files in JSON format {file_type: s3_path}',
               existing_nullable=False)
    op.alter_column('reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When current version was generated (denormalized for quick access)',
               existing_comment='Timestamp final when report was generated in UTC',
               existing_nullable=True)
    op.create_index('idx_reports_current_version', 'reports', ['current_version'], unique=False)
    op.create_index('idx_reports_status', 'reports', ['status'], unique=False)
    op.create_unique_constraint(None, 'reports', ['id'])
    op.create_unique_constraint(None, 'tables', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    
    # ### CUSTOM DATA MIGRATION ###
    # Migrate existing reports: create version 1 for each report and link all cards
    connection = op.get_bind()
    
    # Get all existing reports
    result = connection.execute(sa.text("SELECT id, s3_uri, created_at, generated_at FROM reports"))
    reports = result.fetchall()
    
    import uuid
    import json
    
    for report in reports:
        report_id = report[0]
        s3_uri = report[1]
        created_at = report[2]
        generated_at = report[3]
        
        # Generate a new UUID for the version
        version_id = str(uuid.uuid4())
        
        # Check if this report has any cards
        cards_check_result = connection.execute(sa.text("""
            SELECT COUNT(*) 
            FROM cards 
            WHERE report_id = :report_id 
            AND is_deleted = false
        """), {'report_id': report_id})
        
        has_cards = cards_check_result.scalar() > 0
        
        # Set status based on report generation state and card existence
        # If generated_at is set -> output-generated (report was successfully generated)
        # If generated_at is null but cards exist -> analysis-completed (cards generated, report not yet)
        # If generated_at is null and no cards -> draft (chat just started)
        if generated_at is not None:
            initial_status = 'output-generated'
        elif has_cards:
            initial_status = 'analysis-completed'
        else:
            initial_status = 'draft'
        
        # Serialize s3_uri as JSON string
        s3_uri_json = json.dumps(s3_uri) if s3_uri else None
        
        # Use generated_at for last_activity_at, fallback to created_at if null
        last_activity = generated_at if generated_at else created_at
        
        # Insert initial version (version 1)
        connection.execute(sa.text("""
            INSERT INTO report_versions (id, report_id, version, s3_uri, generated_at, is_active, status, last_activity_at, created_at)
            VALUES (:version_id, :report_id, 1, CAST(:s3_uri AS jsonb), :generated_at, true, :status, :last_activity_at, :created_at)
        """), {
            'version_id': version_id,
            'report_id': report_id,
            's3_uri': s3_uri_json,
            'generated_at': generated_at,
            'status': initial_status,
            'last_activity_at': last_activity,
            'created_at': created_at
        })
        
        # Update report with initial status and last_activity_at
        connection.execute(sa.text("""
            UPDATE reports 
            SET status = :status, 
                last_activity_at = :last_activity_at,
                current_version = 1
            WHERE id = :report_id
        """), {
            'status': initial_status,
            'last_activity_at': last_activity,
            'report_id': report_id
        })
        
        # Get all active cards for this report
        cards_result = connection.execute(sa.text("""
            SELECT id, sequence 
            FROM cards 
            WHERE report_id = :report_id 
            AND is_deleted = false
            ORDER BY sequence
        """), {'report_id': report_id})
        
        cards = cards_result.fetchall()
        
        # Link each card to the version
        for card in cards:
            card_id = card[0]
            sequence = card[1]
            mapping_id = str(uuid.uuid4())
            
            connection.execute(sa.text("""
                INSERT INTO report_version_cards (id, report_version_id, parent_card_id, sequence, is_modified, created_at)
                VALUES (:mapping_id, :version_id, :card_id, :sequence, false, :created_at)
            """), {
                'mapping_id': mapping_id,
                'version_id': version_id,
                'card_id': card_id,
                'sequence': sequence,
                'created_at': created_at
            })
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tables', type_='unique')
    op.drop_constraint(None, 'reports', type_='unique')
    op.drop_index('idx_reports_status', table_name='reports')
    op.drop_index('idx_reports_current_version', table_name='reports')
    op.alter_column('reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp final when report was generated in UTC',
               existing_comment='When current version was generated (denormalized for quick access)',
               existing_nullable=True)
    op.alter_column('reports', 's3_uri',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='S3 URIs to the report files in JSON format {file_type: s3_path}',
               existing_comment='S3 URIs of current version (denormalized for quick access)',
               existing_nullable=False)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when report markdown was generated',
               existing_comment='Timestamp when report was first created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('reports', 'last_activity_at')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'current_version')
    op.drop_column('reports', 'poster_image_url')
    op.drop_constraint(None, 'publish', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    op.alter_column('messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Whether the chat has been deleted by the user',
               existing_nullable=False)
    op.drop_constraint(None, 'cards', type_='unique')
    op.alter_column('cards', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Whether the card is deleted',
               existing_nullable=False)
    op.alter_column('cards', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='Whether the card is active',
               existing_nullable=False)
    op.alter_column('cards', 'report_id',
               existing_type=sa.CHAR(length=36),
               comment=None,
               existing_comment='Reference to base report for filtering',
               existing_nullable=False)
    op.alter_column('cards', 'card_id',
               existing_type=sa.CHAR(length=36),
               comment='Card identifier',
               existing_comment='Business card identifier - links versions of same logical card',
               existing_nullable=False)
    op.alter_column('cards', 'id',
               existing_type=sa.CHAR(length=36),
               comment='parent card id since we have to store version of the card',
               existing_comment='Primary key - unique for each card instance',
               existing_nullable=False)
    op.drop_constraint(None, 'card_versions', type_='unique')
    op.drop_index('idx_report_version_cards_version_id', table_name='report_version_cards')
    op.drop_index('idx_report_version_cards_sequence', table_name='report_version_cards')
    op.drop_index('idx_report_version_cards_parent_card_id', table_name='report_version_cards')
    op.drop_table('report_version_cards')
    op.drop_index('idx_report_versions_version', table_name='report_versions')
    op.drop_index('idx_report_versions_status', table_name='report_versions')
    op.drop_index('idx_report_versions_report_id', table_name='report_versions')
    op.drop_index('idx_report_versions_is_active', table_name='report_versions')
    op.drop_table('report_versions')
    # ### end Alembic commands ###
