"""Made description in requests table as nullable

Revision ID: eb19fa22cf92
Revises: 1585890b7b93
Create Date: 2025-09-21 00:27:59.834219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb19fa22cf92'
down_revision: Union[str, None] = '1585890b7b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Description of the request')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Description of the request')
    # ### end Alembic commands ###
